### ISSUE TITLE
Some labels aren't idiomatic

### ISSUE THREAD

**Issue by analytik** [ujamii/prometheus-sentry-exporter#10]
Labels like `issue_first_seen` and `issue_last_seen` are a poor use of labels, because

1. Having a very high cardinality for labels is an prometheus antipattern
2. You never want to show a graph for an issue "where issue_first_seen is 2020-03-23T12:00:06.430Z", so you shouldn't report it as a label

This, instead, should be a separate metric (e.g. age since last/first seen in seconds), or should be ignored, or at least reduced to "year-month" format, for example if someone wants to know how often old issues resurface.

**Comment by mgrundkoetter** [comment]
Yes, you are right. There has already been some discussion about this in #5. You are more than welcome to propose a PR for this change.

**Comment by analytik** [comment]
Ah, noted. Sadly, I don't dabble in PHP anymore, so I'll try to come up with another way to fix this on our side. Thanks for replying so quickly though!
