### ISSUE TITLE
'issue_logger' is NULL

### ISSUE THREAD

**Issue by marcindulak** [ujamii/prometheus-sentry-exporter#2]
Accessing http://localhost/metrics/ gives:

```
Fatal error: Uncaught TypeError: Argument 2 passed to OpenMetricsPhp\Exposition\Text\Types\Label::fromNameAndValue() must be of the type string, null given, called in /var/www/html/src/SentryExporter.php on line 65 and defined in /var/www/html/vendor/openmetrics-php/exposition-text/src/Types/Label.php:44 Stack trace: #0 /var/www/html/src/SentryExporter.php(65): OpenMetricsPhp\Exposition\Text\Types\Label::fromNameAndValue('issue_logger', NULL) #1 /var/www/html/metrics/index.php(6): Ujamii\OpenMetrics\Sentry\SentryExporter->run() #2 {main} thrown in /var/www/html/vendor/openmetrics-php/exposition-text/src/Types/Label.php on line 44
```

https://github.com/ujamii/prometheus-sentry-exporter/blob/337de7dbd4b467b4530e9d33dad8fa0d175242e5/src/SentryExporter.php#L65

**Comment by mgrundkoetter** [comment]
Which sentry version are you using?

**Comment by marcindulak** [comment]
https://sentry.io/ "Team" pricing plan, I'm not sure they provide an explicit versioning.

What permissions are required by the Auth Token for prometheus-sentry-exporter?
Will `event:read, member:read, org:read, project:read, project:releases, team:read` be enough?

**Comment by mgrundkoetter** [comment]
Im not sure, but as far as I can remember, event:read and project:read were enough. We use a self hosted sentry, I do not have any experience with the sentry.io version.

**Comment by marcindulak** [comment]
`ujamii/prometheus-sentry-exporter:0.4.1` works for me - no more `Uncaught TypeError`.
