### ISSUE TITLE
officially allocate port number @prometheus

### ISSUE THREAD

**Issue by marcindulak** [ujamii/prometheus-sentry-exporter#3]
https://github.com/prometheus/prometheus/wiki/Default-port-allocations

**Comment by mgrundkoetter** [comment]
You can map whichever port you like when you use docker, so no need to set a specific one inside the container, see https://docs.docker.com/config/containers/container-networking/#published-ports

**Comment by marcindulak** [comment]
I could use any port, and probably will use `9412` for the prometheus target, since this is the port which https://github.com/snakecharmer/sentry_exporter registered on https://github.com/prometheus/prometheus/wiki/Default-port-allocations.
